server:
  port: 8882
spring:
  application:
    name: config-client
#  RabbitMq的地址、端口、用户名、密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
#      指明远程仓库的分支
      label: master
#      配置文件名称：dev 开发环境，test 测试环境，pro 生产环境
      profile: dev
#      配置服务中心网址
      uri: http://localhost:8888
#高可用的分布式配置中心改造之处：指定服务注册中心地址-------------------------
      discovery:
#        从配置中心读取文件
        enabled: true
#        配置中心的servieId，即服务名
        serviceId: config-server
#服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#management.endpoints.web.exposure.include=bus-refresh
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh

