server:
  port: 8762
#应用名称，服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service-hi
#指定服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#    service-url: http://localhost:8761/eureka