server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        配置git仓库
        git:
#          git仓库地址
#          uri: https://github.com/forezp/SpringcloudConfig/
          uri: https://github.com/litangbo/sc-f-chapter1
#          git仓库路径 repository 仓库的正确拼写
#          search-paths: respo
          search-paths: repo
#          访问git仓库的用户名和密码
#          若Git仓库为公开仓库，则可以不填写用户名和密码；若是私有仓库，则需要填写，本例子是公开仓库
          username:
          password:
#      git仓库的分支
      label: master
#高可用的分布式配置中心改造之处：指定服务注册中心地址-------------------------
eureka:
  client:
    serviceUrl:
#      因为服务注册中心eureka-server的端口没有改成8889，所以还是用8761端口
#      defaultZone: http://localhost:8889/eureka
      defaultZone: http://localhost:8761/eureka
